apiVersion: v1
kind: Pod
metadata:
  name: nginx-clusterip
  labels:
    name: nginx-clusterip
    app: test-clusterip
spec:
  containers:
  - name: nginx-clusterip
    image: nginx
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80


---

apiVersion: v1
kind: Service
metadata:
  name: clusterip-svc
spec:
  selector:
    name: nginx-clusterip
    app: test-clusterip
  ports:
  - port: 8080
    targetPort: 80
