apiVersion: v1
kind: Pod
metadata:
  name: nginx-nodeport
  labels:
    name: nginx-nodeport
    app: test-nodeport
spec:
  containers:
  - name: nginx-nodeport
    image: nginx
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80


---

apiVersion: v1
kind: Service
metadata:
  name: nodeport-svc
spec:
  type: NodePort
  selector:
    name: nginx-nodeport
    app: test-nodeport
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 80
    nodePort: 30005
