apiVersion: v1
kind: Pod
metadata:
  name: nginx-lb
  labels:
    name: nginx-lb
    app: test-lb
spec:
  containers:
  - name: nginx-lb
    image: nginx
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80


---

apiVersion: v1
kind: Service
metadata:
  name: lb-svc
spec:
  type: LoadBalancer
  selector:
    name: nginx-lb
    app: test-lb
  ports:
  - protocol: TCP
    port: 8081
    targetPort: 80