apiVersion: v1
kind: Pod
metadata:
  name: my-nginx
  namespace: "saiteja"
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80
    resources:
      requests:
        memory: "64Mi"
        cpu: 250m
      limits:
        memory: "128Mi"
        cpu: 500m