apiVersion: v1
kind: Pod
metadata:
  name: my-nginx
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80
    env:
      - name: FIRSTNAME
        valueFrom:
            configMapKeyRef:
              name: test-configmap
              key: firstName
      - name: LASTNAME
        valueFrom:
            configMapKeyRef:
              name: test-configmap
              key: lastName