apiVersion: v1
kind: Pod
metadata:
  name: secret-pod1
  labels:
    name: secret-pod1
spec:
  containers:
  - name: secret-container
    image: nginx:latest
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
    env:
      - name: USERNAME
        valueFrom:
          secretKeyRef:
            name: mysecret
            key: username
      - name: PASSWORD
        valueFrom:
          secretKeyRef:
            name: mysecret
            key: password


---

apiVersion: v1
kind: Pod
metadata:
  name: secret-pod2
  labels:
    name: secret-pod2
spec:
  containers:
  - name: secret-container
    image: nginx
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
    envFrom:
      - secretRef:
          name: mysecret
